name: Deploy to Azure

on:
  workflow_run:
    workflows: [ "CodeQL" ]
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: '🔍 Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: '📦 Build and Push Docker image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/golden-eye:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/golden-eye:latest

      - name: '🚀 Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'golden-eye'
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/golden-eye:latest